on:
  repository_dispatch:
    types:
      - my-custom-type
jobs:
  dispatch:
    name: Workflow dispatch events
    runs-on: ubuntu-latest

    steps:
      - name: Hello
        run: |
          echo "hello"
